# Task 1:
Read and write both CSV and JSON files; parse and filter specific records.

In [ ]:
# import libraries
import pandas as pd

df = pd.read_csv("students.csv")

# Desplay the dataframe top 5 rows used head() function 
df.head()

In [ ]:
# read the datafram into CSV_file 
df.to_csv("new_students.csv", index=False)

In [ ]:
# read a json file into dataframe
df = pd.read_json("students.json")

# desplay the dataframe
print(df)

In [ ]:
# read the dataframe file into json file

df.to_json("students_output.json", orient="records", indent=4)

# Task 2:
Practice NumPy: create arrays, index/slice them, and compute basic statistics without loops.

In [ ]:
import numpy as np

# create the array 
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print("-----")

# creating the 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

print("-----")

# create the 3D array
arr3 = np.array([[[1,2,3], [3,2,1]], [[4,5,6], [6,5,4]]])
print(arr3)

[1 2 3 4 5 6 7 8 9]
-----
[[1 2 3]
 [4 5 6]]
-----
[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]]
3

In [19]:
# index and slice the array array[start:stop:step]
print(arr1[3:7])

print('----')
print(arr1[:6])

print("----")
print(arr[:9:2])

print("----")
print(arr1[4: :2])

print('----')
arr[::2]

[4 5 6 7]
----
[1 2 3 4 5 6]
----
[1 3 5 7 9]
----
[5 7 9]
----

array([1, 3, 5, 7, 9])

In [ ]:
# sliing the 2D array
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [27]:
# print the first 2 rows
print(arr2[:2])

print("----")
# for columns
print(arr2[:, 1])
print("----")
print(arr2[:, 0])

[[1 2 3]
 [4 5 6]]
----
[2 5 8]
----
[1 4 7]

In [28]:
# create the array and perform the some function
arr = np.array([10,20,30,40,50])

In [32]:
# used build function
print(arr.sum()) # sum function is used to add the all elements of array

print("---")
# find the minimum values 
print(arr.min())

print('----')
# find the maximum values 
print(arr.max())

150
---
10
----
50

In [36]:
# mean of the array
print(arr.mean())

print("---")
# median of the array
print(np.median(arr))

print("----")
arr.std()

30.0
---
30.0
----

14.142135623730951

In [38]:
arr.var()
arr.size

5

# Task 3:
Practice Pandas: load a dataset, filter rows, group by a column, and handle missing values.

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("students.csv")

# Display data
print(df.head())

# Filter students with marks greater than 80
print(df[df['Marks'] > 80])

# Average marks by department
print(df.groupby('Department')['Marks'].mean())

# Check missing values
print(df.isnull().sum())

# Replace missing values with the mean
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

# Display updated data
print(df)

# Task 4:
Merge two small datasets (dictionaries or DataFrames) and produce a summary.

In [39]:
import pandas as pd

students = {
    'ID':[1,2,3,4],
    'Name':['Ali','Sara','Ahmed','Ayesha']
}

marks = {
    'ID':[1,2,3,4],
    'Marks':[85,90,78,95]
}

df_students = pd.DataFrame(students)
df_marks = pd.DataFrame(marks)

In [40]:
# print the students dataframe
print(df_students)

   ID    Name
0   1     Ali
1   2    Sara
2   3   Ahmed
3   4  Ayesha

In [41]:
print(df_marks)

   ID  Marks
0   1     85
1   2     90
2   3     78
3   4     95

In [44]:
# merged the dataframe into single dataframe
merged_df = pd.merge(df_students, df_marks, on="ID")
print(merged_df)

   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95

# types of merge function

In [50]:
# 1 inner join
merged_inner = pd.merge(df_students, df_marks, on="ID", how='inner')
print(merged_inner)

print("----")
# left join
merged_left = pd.merge(df_students, df_marks, on="ID", how='left')
print(merged_left)

print("----")
# right join 
merged_right = pd.merge(df_students, df_marks, on="ID", how='right')
print(merged_right)

print("----")
merged_outer = pd.merge(df_students, df_marks, on='ID', how='outer')
print(merged_outer)

   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95
----
   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95
----
   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95
----
   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95

In [51]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   Name    4 non-null      str
 2   Marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [52]:
merged_df.describe()

             ID     Marks
count  4.000000   4.00000
mean   2.500000  87.00000
std    1.290994   7.25718
min    1.000000  78.00000
25%    1.750000  83.25000
50%    2.500000  87.50000
75%    3.250000  91.25000
max    4.000000  95.00000

In [54]:
# Average Marks
print(merged_df['Marks'].mean())

print("---")
# Highest Marks
print(merged_df['Marks'].max())

print("---")
# Lowest Marks
print(merged_df['Marks'].min())

print("---")
# Total Marks
print(merged_df['Marks'].sum())

87.0
---
95
---
78
---
348

In [56]:
merged_df['Department'] = ['CS','CS','IT','IT']
merged_df

   ID    Name  Marks Department
0   1     Ali     85         CS
1   2    Sara     90         CS
2   3   Ahmed     78         IT
3   4  Ayesha     95         IT

In [57]:
merged_df.groupby('Department')['Marks'].mean()

Department
CS    87.5
IT    86.5
Name: Marks, dtype: float64

In [58]:
# combine code 
import pandas as pd

students = {
    'ID':[1,2,3,4],
    'Name':['Ali','Sara','Ahmed','Ayesha']
}

marks = {
    'ID':[1,2,3,4],
    'Marks':[85,90,78,95]
}

df_students = pd.DataFrame(students)
df_marks = pd.DataFrame(marks)

merged_df = pd.merge(df_students, df_marks, on='ID')

print(merged_df)

print("\nAverage Marks:", merged_df['Marks'].mean())
print("Highest Marks:", merged_df['Marks'].max())
print("Lowest Marks:", merged_df['Marks'].min())
print("Total Marks:", merged_df['Marks'].sum())

print("\nSummary Statistics:")
print(merged_df.describe())

   ID    Name  Marks
0   1     Ali     85
1   2    Sara     90
2   3   Ahmed     78
3   4  Ayesha     95

Average Marks: 87.0
Highest Marks: 95
Lowest Marks: 78
Total Marks: 348

Summary Statistics:
             ID     Marks
count  4.000000   4.00000
mean   2.500000  87.00000
std    1.290994   7.25718
min    1.000000  78.00000
25%    1.750000  83.25000
50%    2.500000  87.50000
75%    3.250000  91.25000
max    4.000000  95.00000

# Task 5

In [2]:
import logging

logging.basicConfig(
    filename="errors.log",
    level=logging.ERROR,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

class InvalidAgeError(Exception):
    pass

try:
    age = 15

    if age < 18:
        raise InvalidAgeError("Age must be 18 or older.")

except InvalidAgeError as e:
    logging.error(e)

2026-09-06 22:55:23,505 - ERROR - Age must be 18 or older.